 @startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class FindDealCommand
Class DeleteClientCommand
Class AddDealCommand
Class UpdateDealCommand

package "Parser classes" {
Class "<<interface>>\nParser" as Parser
Class AddressBookParser
Class FindDealCommandParser
Class AddDealCommandParser
Class UpdateDealCommandParser
Class DeleteClientCommandParser
Class "{abstract}\nDeleteCommandParser" as DeleteCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> FindDealCommandParser : <<create>>
AddressBookParser .down.> AddDealCommandParser : <<create>>
AddressBookParser .down.> UpdateDealCommandParser : <<create>>
AddressBookParser .down.> DeleteClientCommandParser : <<create>>

FindDealCommandParser ..> FindDealCommand : <<create>>
AddDealCommandParser ..> AddDealCommand : <<create>>
UpdateDealCommandParser ..> UpdateDealCommand : <<create>>
DeleteClientCommandParser ..> DeleteClientCommand : <<create>>
AddressBookParser ..> Command : <<use>>
FindDealCommandParser .up.|> Parser
AddDealCommandParser .up.|> Parser
UpdateDealCommandParser .up.|> Parser
DeleteClientCommandParser -up-|> DeleteCommandParser
DeleteCommandParser .up.|> Parser

FindDealCommandParser ..> ArgumentMultimap
AddDealCommandParser ..> ArgumentMultimap
UpdateDealCommandParser ..> ArgumentMultimap
DeleteClientCommandParser ..> ArgumentMultimap

FindDealCommandParser ..> ArgumentTokenizer
AddDealCommandParser ..> ArgumentTokenizer
UpdateDealCommandParser ..> ArgumentTokenizer
DeleteClientCommandParser ..> ArgumentTokenizer

ArgumentTokenizer .left.> ArgumentMultimap

FindDealCommandParser ..> CliSyntax
AddDealCommandParser ..> CliSyntax
UpdateDealCommandParser ..> CliSyntax
DeleteClientCommandParser ..> CliSyntax

CliSyntax ..> Prefix
FindDealCommandParser ..> ParserUtil
AddDealCommandParser ..> ParserUtil
UpdateDealCommandParser ..> ParserUtil
DeleteClientCommandParser ..> ParserUtil

ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
FindDealCommand -up-|> Command
AddDealCommand -up-|> Command
UpdateDealCommand -up-|> Command
DeleteClientCommand -up-|> Command
@enduml
