@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class FindDealCommand
Class DeleteClientCommand

package "Parser classes" {
Class "<<interface>>\nParser" as Parser
Class AddressBookParser
Class FindDealCommandParser
Class DeleteClientCommandParser
Class "{abstract}\nDeleteCommandParser" as DeleteCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> FindDealCommandParser : <<create>>
AddressBookParser .down.> DeleteClientCommandParser : <<create>>

FindDealCommandParser ..> FindDealCommand : <<create>>
DeleteClientCommandParser ..> DeleteClientCommand : <<create>>
AddressBookParser ..> Command : <<use>>
FindDealCommandParser .up.|> Parser
DeleteClientCommandParser -up-|> DeleteCommandParser
DeleteCommandParser .up.|> Parser

FindDealCommandParser ..> ArgumentMultimap
DeleteClientCommandParser ..> ArgumentMultimap

FindDealCommandParser ..> ArgumentTokenizer
DeleteClientCommandParser ..> ArgumentTokenizer

ArgumentTokenizer .left.> ArgumentMultimap

FindDealCommandParser ..> CliSyntax
DeleteClientCommandParser ..> CliSyntax

CliSyntax ..> Prefix
FindDealCommandParser ..> ParserUtil
DeleteClientCommandParser ..> ParserUtil

ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
FindDealCommand -up-|> Command
DeleteClientCommand -up-|> Command
@enduml
